# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-vpc
  description: This component is responsible for provisioning a VPC and corresponding Subnets
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





